name: Docker GHA
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  job1:
    runs-on:
      - ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: business
        uses: ./
